name: Test Application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  test:
    name: Run test
    runs-on: unbuntu-latest

    steps:
      - name: Checkout code
        uses: actions/setup-node@v4
        
      - name: setup node.js
        run: npm install

      - name: Run tests
        run: npm test
